//---------------------------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by peppapig from database table definition.
//	Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web.Http;
using LinqToDB;
using LinqToDB.Data;

using peppa.Domain;

namespace MockWebAPI.Controllers
{
	/// <summary>
	/// アカウントのWebAPI
	/// </summary>
	[RoutePrefix("api/account")]
	public partial class AccountController : ApiController
	{
		/// <summary>
		/// アカウントの検索
		/// </summary>
		/// <param name="c"></param>
		/// <returns></returns>
		[HttpGet, Route("search")]
		public IEnumerable<Account> Search([FromUri]AccountCondition c)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var list =
					c == null ? db.Account.ToList() :
					db.Account.Where(c.CreatePredicate()).ToList();
				return list;
			}
		}

		/// <summary>
		/// アカウントの取得
		/// </summary>
		/// <param name="accountId">アカウントID(account_id)</param>
		/// <returns></returns>
		[HttpGet, Route("get/{accountId}")]
		public Account Get(int accountId)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var o = db.Account.Find(accountId);
				return o;
			}
		}

		/// <summary>
		/// アカウントの作成
		/// </summary>
		/// <param name="o"></param>
		/// <returns>uid</returns>
		[HttpPost, Route("create")]
		public int Post([FromBody]Account o)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				int uid = (int)db.InsertWithIdentity<Account>(o);
				return uid;
			}
		}

		/// <summary>
		/// アカウントの更新
		/// </summary>
		/// <param name="accountId">アカウントID(account_id)</param>
		/// <param name="o"></param>
		/// <returns>更新件数</returns>
		[HttpPut, Route("modify/{accountId}")]
		public int Modify(int accountId, [FromBody]Account o)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var count = db.Update<Account>(o);
				return count;
			}
		}

		/// <summary>
		/// アカウントの削除(論理)
		/// </summary>
		/// <param name="accountId">アカウントID(account_id)</param>
		[HttpDelete, Route("remove/{accountId}")]
		public int Remove(int accountId)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var o = db.Account.Find(accountId);
				o.removed_at = DateTime.Now;
				var count = db.Update<Account>(o);
				return count;
			}
		}
	}
}
