//---------------------------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by peppapig from database table definition.
//	Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web.Http;
using LinqToDB;
using LinqToDB.Data;

using peppa.Domain;

namespace MockWebAPI.Controllers
{
	/// <summary>
	/// 連絡先種別のWebAPI
	/// </summary>
	[RoutePrefix("api/contacttype")]
	public partial class ContactTypeController : ApiController
	{
		/// <summary>
		/// 連絡先種別の検索
		/// </summary>
		/// <param name="c"></param>
		/// <returns></returns>
		[HttpGet, Route("search")]
		public IEnumerable<ContactType> Search([FromUri]ContactTypeCondition c)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var list =
					c == null ? db.ContactType.ToList() :
					db.ContactType.Where(c.CreatePredicate()).ToList();
				return list;
			}
		}

		/// <summary>
		/// 連絡先種別の取得
		/// </summary>
		/// <param name="contactTypeId">連絡先種別ID(contact_type_id)</param>
		/// <returns></returns>
		[HttpGet, Route("get/{contactTypeId}")]
		public ContactType Get(int contactTypeId)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var o = db.ContactType.Find(contactTypeId);
				return o;
			}
		}

		/// <summary>
		/// 連絡先種別の作成
		/// </summary>
		/// <param name="o"></param>
		/// <returns>作成件数</returns>
		[HttpPost, Route("create")]
		public int Post([FromBody]ContactType o)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var count = db.Insert<ContactType>(o);
				return count;
			}
		}

		/// <summary>
		/// 連絡先種別の更新
		/// </summary>
		/// <param name="contactTypeId">連絡先種別ID(contact_type_id)</param>
		/// <param name="o"></param>
		/// <returns>更新件数</returns>
		[HttpPut, Route("modify/{contactTypeId}")]
		public int Modify(int contactTypeId, [FromBody]ContactType o)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var count = db.Update<ContactType>(o);
				return count;
			}
		}

		/// <summary>
		/// 連絡先種別の削除(論理)
		/// </summary>
		/// <param name="contactTypeId">連絡先種別ID(contact_type_id)</param>
		[HttpDelete, Route("remove/{contactTypeId}")]
		public int Remove(int contactTypeId)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var o = db.ContactType.Find(contactTypeId);
				o.removed_at = DateTime.Now;
				var count = db.Update<ContactType>(o);
				return count;
			}
		}
	}
}
