//---------------------------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by peppapig from database table definition.
//	Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web.Http;
using LinqToDB;
using LinqToDB.Data;

using peppa.Domain;

namespace MockWebAPI.Controllers
{
	/// <summary>
	/// エラーログのWebAPI
	/// </summary>
	[RoutePrefix("api/errorlog")]
	public partial class ErrorLogController : ApiController
	{
		/// <summary>
		/// エラーログの検索
		/// </summary>
		/// <param name="c"></param>
		/// <returns></returns>
		[HttpGet, Route("search")]
		public IEnumerable<ErrorLog> Search([FromUri]ErrorLogCondition c)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var list =
					c == null ? db.ErrorLog.ToList() :
					db.ErrorLog.Where(c.CreatePredicate()).ToList();
				return list;
			}
		}

		/// <summary>
		/// エラーログの取得
		/// </summary>
		/// <param name="uid">ユニークID(uid)</param>
		/// <returns></returns>
		[HttpGet, Route("get/{uid}")]
		public ErrorLog Get(int uid)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var o = db.ErrorLog.Find(uid);
				return o;
			}
		}

		/// <summary>
		/// エラーログの作成
		/// </summary>
		/// <param name="o"></param>
		/// <returns>作成件数</returns>
		[HttpPost, Route("create")]
		public int Post([FromBody]ErrorLog o)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var count = db.Insert<ErrorLog>(o);
				return count;
			}
		}

		/// <summary>
		/// エラーログの更新
		/// </summary>
		/// <param name="uid">ユニークID(uid)</param>
		/// <param name="o"></param>
		/// <returns>更新件数</returns>
		[HttpPut, Route("modify/{uid}")]
		public int Modify(int uid, [FromBody]ErrorLog o)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var count = db.Update<ErrorLog>(o);
				return count;
			}
		}

		/// <summary>
		/// エラーログの削除(論理)
		/// </summary>
		/// <param name="uid">ユニークID(uid)</param>
		[HttpDelete, Route("remove/{uid}")]
		public int Remove(int uid)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var o = db.ErrorLog.Find(uid);
				o.removed_at = DateTime.Now;
				var count = db.Update<ErrorLog>(o);
				return count;
			}
		}
	}
}
