//---------------------------------------------------------------------------------------------------
// <auto-generated>
//	This code was generated by peppapig from database table definition.
//	Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web.Http;
using LinqToDB;
using LinqToDB.Data;

using peppa.Domain;

namespace MockWebAPI.Controllers
{
	/// <summary>
	/// ロールマスタのWebAPI
	/// </summary>
	[RoutePrefix("api/role")]
	public partial class RoleController : ApiController
	{
		/// <summary>
		/// ロールマスタの検索
		/// </summary>
		/// <param name="c"></param>
		/// <returns></returns>
		[HttpGet, Route("search")]
		public IEnumerable<Role> Search([FromUri]RoleCondition c)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var list =
					c == null ? db.Role.ToList() :
					db.Role.Where(c.CreatePredicate()).ToList();
				return list;
			}
		}

		/// <summary>
		/// ロールマスタの取得
		/// </summary>
		/// <param name="roleId">ロールID(role_id)</param>
		/// <returns></returns>
		[HttpGet, Route("get/{roleId}")]
		public Role Get(string roleId)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var o = db.Role.Find(roleId);
				return o;
			}
		}

		/// <summary>
		/// ロールマスタの作成
		/// </summary>
		/// <param name="o"></param>
		/// <returns>作成件数</returns>
		[HttpPost, Route("create")]
		public int Post([FromBody]Role o)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var count = db.Insert<Role>(o);
				return count;
			}
		}

		/// <summary>
		/// ロールマスタの更新
		/// </summary>
		/// <param name="roleId">ロールID(role_id)</param>
		/// <param name="o"></param>
		/// <returns>更新件数</returns>
		[HttpPut, Route("modify/{roleId}")]
		public int Modify(string roleId, [FromBody]Role o)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var count = db.Update<Role>(o);
				return count;
			}
		}

		/// <summary>
		/// ロールマスタの削除(論理)
		/// </summary>
		/// <param name="roleId">ロールID(role_id)</param>
		[HttpDelete, Route("remove/{roleId}")]
		public int Remove(string roleId)
		{
#if DEBUG
			DataConnection.TurnTraceSwitchOn();
			DataConnection.WriteTraceLine = (msg, context) => Debug.WriteLine(msg, context);
#endif
			using (var db = new peppaDB())
			{
				var o = db.Role.Find(roleId);
				o.removed_at = DateTime.Now;
				var count = db.Update<Role>(o);
				return count;
			}
		}
	}
}
